"""
F1Intel — Race Story Storage
Generated race stories are cached to local JSON files in data/race_stories/
so visiting the same race's story page twice doesn't burn a second API
call — generation happens once, then it's read from disk forever after
(until explicitly regenerated by the user).

File layout: data/race_stories/{season}_{round}.json
"""

from __future__ import annotations
import os
import json
import time

STORY_DIR = os.path.join(os.path.dirname(os.path.dirname(__file__)), "data", "race_stories")
os.makedirs(STORY_DIR, exist_ok=True)


def _story_path(season: int, round_num) -> str:
    return os.path.join(STORY_DIR, f"{season}_{round_num}.json")


def load_story(season: int, round_num) -> dict | None:
    """Return the cached story dict, or None if it hasn't been generated yet."""
    path = _story_path(season, round_num)
    if not os.path.exists(path):
        return None
    try:
        with open(path, "r", encoding="utf-8") as f:
            return json.load(f)
    except Exception:
        return None


def save_story(season: int, round_num, race_name: str, story_text: str) -> bool:
    """Persist a generated story to disk. Returns True on success."""
    path = _story_path(season, round_num)
    payload = {
        "season": season,
        "round": round_num,
        "race_name": race_name,
        "story_text": story_text,
        "generated_at": time.time(),
    }
    try:
        with open(path, "w", encoding="utf-8") as f:
            json.dump(payload, f, ensure_ascii=False, indent=2)
        return True
    except Exception:
        return False


def delete_story(season: int, round_num) -> bool:
    """Remove a cached story so it can be regenerated fresh."""
    path = _story_path(season, round_num)
    try:
        if os.path.exists(path):
            os.remove(path)
        return True
    except Exception:
        return False


def list_cached_stories(season: int) -> list[dict]:
    """List all cached stories for a season, sorted by round number."""
    results = []
    if not os.path.exists(STORY_DIR):
        return results
    prefix = f"{season}_"
    for fname in os.listdir(STORY_DIR):
        if fname.startswith(prefix) and fname.endswith(".json"):
            try:
                with open(os.path.join(STORY_DIR, fname), "r", encoding="utf-8") as f:
                    results.append(json.load(f))
            except Exception:
                continue
    results.sort(key=lambda r: int(r.get("round", 0)) if str(r.get("round","0")).isdigit() else 0)
    return results
